### PR TITLE
UE 5.3.2 update

### PR DESCRIPTION
**Pull request by alefriant**
Some files modified to run it in UE 5.3.2

### CODE REVIEW

**Comment by alefriant** [comment]
I wasn't able to submit the SDKs v59 because I have no permission and if I want to I can submit only 100 files per time, this (line 11) should be corrected in the readme.me file, sorry this is my first time trying to add something to a public Git... I'm used to Perforce and this is a bit different. TY

**Comment by alefriant** [comment]
Note: 
This fix works in SharedSpaces when tested in PC, the apk builds without errors but the pawn doesn't work in the headset.

**Comment by AlexThiv** [comment]
We updated the project to support UE5.3 with minimal changes. Thanks for providing this PR as it probably unblocked users in the mean time. I will close this now. We also updated the MetaXRPlatform SDK to V59.
https://github.com/oculus-samples/Unreal-SharedSpaces/commit/4543cdca389ef84dacb74e56c77d3b8e18ca9600

**Comment by alefriant** [comment]
awesome, I'll give it a try, thank you!

**Pull request closed without merging**
